[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600
lib_ldf_mode = deep+
lib_deps =
  bogde/HX711@0.7.5
  z3t0/IRremote@4.7.1
  marcoschwartz/LiquidCrystal_I2C@1.1.4
  https://github.com/ArminJo/LightweightServo.git
